title: HMCTS technical guidance

permalink: /:title/

collections_dir: ["pages"]
collections:
  pages:
    output: true

defaults:
  - 
    scope:
      path: "_pages"
    values:
      layout: default