on:
  pull_request:
    branches:
      - source
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4
          architecture: 'x64'
      - run: |
          gem install bundler
          bundle exec middleman build
      - run: bundle exec rake publish
        #if: equals(github.ref, 'refs/head/source')
