on:
  pull_request:
    branches:
      - source
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
          architecture: 'x64'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build
        run: bundle exec middleman build
      - name: Publish
        run: |
          rm -rf build
          bundle exec rake publish
        #if: equals(github.ref, 'refs/head/source')
